import Head from 'next/head'
import { Inter } from '@next/font/google'
import { BsFillMoonStarsFill } from 'react-icons/bs'
import { 
  AiFillGithub,
  AiFillLinkedin, 
  AiOutlineInstagram, 
}  from 'react-icons/ai';
import Image from 'next/image';
import deved from '../public/dev-ed-wave.jpg'
import design from '../public/design.png'
import code from '../public/code.png'
import consulting from '../public/consulting.png'
import web1 from '../public/web1.png'
import web2 from '../public/web2.png'
import web3 from '../public/web3.png'
import web4 from '../public/web4.png'
import web5 from '../public/web5.png'
import web6 from '../public/web6.png'
import { useState } from 'react';


export default function Home() {

  const [darkMode, setDarkMode] = useState(false);

  return (
  
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Chicão Portfólio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-gray-50 px-10 md:px-20 lg:px-40 dark:bg-gray-900 max-w-screen-2xl mx-auto'>
        <section className='min-h-screen '>

          <nav className='py-10 mb-12 flex justify-between'>
            <h1 className='text-xl font-burtons dark:text-white'>developed by chicaofmp</h1>
            <ul className='flex items-center'>
              <li>
                <BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className='cursor-pointer dark:text-yellow-400'/>
              </li>
              <li>
                <a className='bg-gradient-to-r from-cyan-500 to-emerald-400 text-white px-4 py-2 rounded-md ml-8' href="#">Resume</a>
              </li>
            </ul>
          </nav>

          <div className='text-center p-10'>
            <h2 className='text-5xl py-2 text-teal-600 font-medium md:text-6xl'>Francisco Moura</h2>
            <h3 className='text-2xl py-2 medium md:text-3xl dark:text-white'>Web Developer and Data Analyst</h3>
            <p className='text-md py-5 leading-8 text-gray-800 medium md:text-xl max-w-xl mx-auto dark:text-white'>
              Lorem ipsum dolor sit amet consectetur, adipisicing elit. Natus aperiam amet voluptatum ea necessitatibus unde ad et maiores molestias recusandae!
            </p>
          </div>

          <div className='text-5xl flex justify-center gap-16 py-3 text-gray-600'>
            <a href="https://github.com/chicaofmp">
              <AiFillGithub className='dark:text-white' />
            </a>
            <a href="https://linkedin.com/in/chicaofmp">
              <AiFillLinkedin className='dark:text-white' />
            </a>
            <a href="https://www.instagram.com/chicaofmp">
              <AiOutlineInstagram className='dark:text-white' />
            </a>
          </div>

          <div className='relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 overflow-hidden md:h-96 md:w-96 m-8'>
            <Image src={deved} layout="fill" objectFit='cover' alt='avatar-img'/>
          </div>
        </section>

        <section>
          <div>
            <h3 className='text-3xl py-1 dark:text-white'>Services I offer</h3>
            <p className='text-md py-2 leading-8 text-gray-800 dark:text-gray-200'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Cumque numquam id facilis iusto placeat est saepe! Deserunt quasi quisquam id?<span className='text-teal-500'> agencies </span>Lorem ipsum dolor sit amet. <span className="text-teal-500"> startups </span>Lorem ipsum dolor sit amet consectetur adipisicing elit. Exercitationem dignissimos delectus sint possimus optio excepturi!
            </p>
            <p className='text-md py-2 leading-8 text-gray-800 dark:text-gray-200'>Mussum Ipsum, cacilds vidis litro abertis. Aenean aliquam molestie leo, vitae iaculis nisl.Nec orci ornare consequat. Praesent lacinia ultrices consectetur. 
            </p>
          </div>

          <div className='lg:flex gap-10'>
            <div className='text-center shadow-lg p-10 m-6 rounded-lg bg-gradient-to-r from-slate-100 to-gray-100 dark:bg-cyan-50 hover:scale-110 ease-in-out duration-300'>
              <Image src={design} width={100} height={100}  alt='avatar-img'/>
              <h3 className='text-lg font-medium pt-8 pb-2'>Mussum Rocks</h3>
              <p className='py-2'>
                Mussum Ipsum, cacilds vidis litro abertis. Em pé sem cair, deitado sem dormir, sentado sem cochilar e fazendo pose.Per aumento de cachacis, eu reclamis.
              </p>
              <h4 className='py-4 text-teal-600'>Design tools I use</h4>
              <p class className='py-4 text-gray-800'Name='text-gray-800 py-1'>Photoshop</p>
              <p class className='py-4 text-gray-800'Name='text-gray-800 py-1'>Illustrator</p>
              <p className='text-gray-800 py-1'>Figma</p>
            </div>

            <div className='text-center shadow-lg p-10 m-6 rounded-lg bg-gradient-to-r from-slate-100 to-gray-100 dark:bg-cyan-50 hover:scale-110 ease-in-out duration-300'>
              <Image src={consulting} width={100} height={100}  alt='avatar-img'/>
              <h3 className='text-lg font-medium pt-8 pb-2'>Mussum Rocks</h3>
              <p className='py-2'>
                Mussum Ipsum, cacilds vidis litro abertis. Em pé sem cair, deitado sem dormir, sentado sem cochilar e fazendo pose.Per aumento de cachacis, eu reclamis.
              </p>
              <h4 className='py-4 text-teal-600'>Design tools I use</h4>
              <p class className='py-4 text-gray-800'Name='text-gray-800 py-1'>Photoshop</p>
              <p class className='py-4 text-gray-800'Name='text-gray-800 py-1'>Illustrator</p>
              <p className='text-gray-800 py-1'>Figma</p>
            </div>

            <div className='text-center shadow-lg p-10 m-6 rounded-lg bg-gradient-to-r from-gray-100 to-gray-50 dark:bg-cyan-50 hover:scale-110 ease-in-out duration-300'>
              <Image src={code} width={100} height={100}  alt='avatar-img'/>
              <h3 className='text-lg font-medium pt-8 pb-2'>Mussum Rocks</h3>
              <p className='py-2'>
                Mussum Ipsum, cacilds vidis litro abertis. Em pé sem cair, deitado sem dormir, sentado sem cochilar e fazendo pose.Per aumento de cachacis, eu reclamis.
              </p>
              <h4 className='py-4 text-teal-600'>Design tools I use</h4>
              <p class className='py-4 text-gray-800'Name='text-gray-800 py-1'>Photoshop</p>
              <p class className='py-4 text-gray-800'Name='text-gray-800 py-1'>Illustrator</p>
              <p className='text-gray-800 py-1'>Figma</p>
            </div>
          </div>
        </section>

        <section>
          <div>
            <h3 className='text-3xl py-3 dark:text-white'>Portfólio</h3>
            <p className='text-md py-2 leading-8 text-gray-800 dark:text-gray-200'>
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Cumque numquam id facilis iusto placeat est saepe! Deserunt quasi quisquam id?<span className='text-teal-500'> agencies </span>Lorem ipsum dolor sit amet. <span className="text-teal-500"> startups </span>Lorem ipsum dolor sit amet consectetur adipisicing elit. Exercitationem dignissimos delectus sint possimus optio excepturi!
            </p>             
          </div>
          <div className='flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap'>
            <div className='basis-1/3 flex-1 '>
              <Image 
                src={web1} 
                className='rounded-lg object-cover' 
                width={'100%'} 
                height={'100%'} 
                layout='responsive' 
                alt='web-img'/>
            </div>
            <div className='basis-1/3 flex-1 '>
              <Image 
                src={web2} 
                className='rounded-lg object-cover' 
                width={'100%'} 
                height={'100%'} 
                layout='responsive' 
                alt='web-img'/>
            </div>
            <div className='basis-1/3 flex-1 '>
              <Image 
                src={web3} 
                className='rounded-lg object-cover' 
                width={'100%'} 
                height={'100%'} 
                layout='responsive' 
                alt='web-img'/>
            </div>
            <div className='basis-1/3 flex-1 '>
              <Image 
                src={web4} 
                className='rounded-lg object-cover' 
                width={'100%'} 
                height={'100%'} 
                layout='responsive' 
                alt='web-img'/>
            </div>
            <div className='basis-1/3 flex-1 '>
              <Image 
                src={web5} 
                className='rounded-lg object-cover' 
                width={'100%'} 
                height={'100%'} 
                layout='responsive' 
                alt='web-img'/>
            </div>
            <div className='basis-1/3 flex-1 '>
              <Image 
                src={web6} 
                className='rounded-lg object-cover' 
                width={'100%'} 
                height={'100%'} 
                layout='responsive' 
                alt='web-img'/>
            </div>
          </div>
        </section>
      </main>
    </div>
  )
}
